"""added transaction type

Revision ID: b0c5e22fedfb
Revises: 2c2c12e775ef
Create Date: 2024-09-12 21:19:32.321210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0c5e22fedfb"
down_revision: Union[str, None] = "2c2c12e775ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "transaction_type",
                sa.String(length=50),
                nullable=True,
                default="simple",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_column("transaction_type")

    # ### end Alembic commands ###
